spring.application.name=Capge_boot_one
server.port=8956
spring.datasource.url=jdbc:mysql://localhost:3306/capgispringboot
spring.datasource.username=root
spring.datasource.password=Parth@#rdbms

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true